### ISSUE TITLE
How to pass the option value for headless chrome

### ISSUE THREAD

**Issue by abadraja** [Api2Pdf/api2pdf.node#1]
Hi!

I am trying to pass the option value by executing this script:
```
var Api2Pdf = require('api2pdf');   
var a2pClient = new Api2Pdf('key');

var options =   {
    url: "link",
    inlinePdf: true,
    options: {
      landscape: true,
      printBackground: false,
    }
  }
a2pClient.headlessChromeFromUrl('link', options=options)
    .then(function(result) {
        console.log(result); //successful api call
    }, function(rejected) {
        console.log(rejected); //an error occurred
    }
);


```
But I get the following error:
```
{ success: false,
  error: 'Invalid JSON. Check your payload and validate your requests by following this tutorial: https://www.api2pdf.com/how-to-use-api2pdfs-swaggerhub-to-get-the-most-out-of-our-support-team/' }
```

**Comment by apexdodge** [comment]
Because you are using the node library, you only need to do the following for the options:

(headless chrome only)

`var options = { landscape: true, printBackground: true };`

another example:

    var options = { 
        displayHeaderFooter: true,
        footerTemplate: "<div class=\"page-footer\" style=\"width:100%; text-align:right; font-size:12px;\">Page <span class=\"pageNumber\"></span> of <span class=\"totalPages\"></span></div>"
    };

**Comment by abadraja** [comment]
Still getting the same issue with the options provided above.

**Comment by apexdodge** [comment]
try

    a2pClient.headlessChromeFromUrl('https://www.github.com', true, 'test.pdf', options)
        .then(function(result) {
            console.log(result); //successful api call
        }, function(rejected) {
            console.log(rejected); //an error occurred
        }
    );

I believe the other parameters were missing from the examples.

**Comment by abadraja** [comment]
It worked! 
Thank You!
