### ISSUE TITLE
headerHtml option not working

### ISSUE THREAD

**Issue by codevon** [Api2Pdf/api2pdf.node#11]
For wkhtmltopdf, I added a url 'https://geovea.com/pdf_header.html'  as headerHtml option. 
But it's not working. No any error, any other things are ok. and only the header is empty for each page. btw, the footerHtml is working.
any idea?

```

    const a2pClient = new Api2Pdf(process.env.REACT_APP_PDF_API);
    const { FileUrl } = await a2pClient.wkHtmlToPdf(
      $html.html(),
      {
        inline: false,
        filename: name + ".pdf",
        options: {
          headerHtml: 'https://geovea.com/pdf_header.html',
          marginBottom: 7,
          marginTop: 8,
          marginLeft: 7,
          marginRight: 7,
        }
      }
    );
```

**Comment by apexdodge** [comment]
wkhtml's footer / header by URL is unreliable and should not be used. You should switch to api2pdf's headless chrome endpoints if you wish to use custom HTML for header/footers.
