### ISSUE TITLE
pdfharp/extract-pages and pdfharp/compress

### ISSUE THREAD

**Issue by PoMkaNik** [Api2Pdf/api2pdf.node#12]
Hi!
Do you have plans to add pdfharp/extract-pages and pdfharp/compress to node client lib?

**Comment by mattpmoreno** [comment]
Same question as above

**Comment by mattpmoreno** [comment]
Opened [PR](https://github.com/Api2Pdf/api2pdf.node/pull/13)

**Comment by apexdodge** [comment]
Thank you for your contribution. We have also added pdfsharpExtractPages.

v2.0.3 is on npm.
