### ISSUE TITLE
Is there a zip function ?

### ISSUE THREAD

**Issue by sabativi** [Api2Pdf/api2pdf.node#15]
I do not see anything whereas is in the doc there is zip function ?

**Comment by apexdodge** [comment]
Only through the REST API directly, not with the client side library.

Thanks

**Comment by sabativi** [comment]
I do not know what to do with the response how to save it to a file ?

```
  fs.writeFile('./test.zip', content, function (err) {
    console.log(err);
  });
```

But the generated file is not correct
