### ISSUE TITLE
Add try-catch around JSON.parse of request

### ISSUE THREAD

**Issue by apexdodge** [Api2Pdf/api2pdf.node#5]
This code block:

![image](https://user-images.githubusercontent.com/777005/73123467-44aebf00-3f5e-11ea-9e55-c610c331bcea.png)

In case of complete API failure to respond, JSON is not returned and it results in exception here. Try-catch can be added to protect.

**Comment by jhchill666** [comment]
+1
Am experiencing errors here as well

**Comment by apexdodge** [comment]
Fixed and released in 1.1.1. https://github.com/Api2Pdf/api2pdf.node/pull/9
