### ISSUE TITLE
How to send local file instead of hosted ppt url

### ISSUE THREAD

**Issue by prathyushaapty** [Api2Pdf/api2pdf.node#7]
currently it is only supporting http or https
Is there a way to send file from local system or ppt buffer.
I would like to convert ppt to pdf

**Comment by apexdodge** [comment]
Sorry no, we only support ingestion from a URL. Best practice is to write code to upload your file to a file storage provider like S3, Azure Blob, or Google Cloud Storage and provide URL from there.
