### ISSUE TITLE
Request deprecation (dependency) 

### ISSUE THREAD

**Issue by Beatboxace** [Api2Pdf/api2pdf.node#8]
Hi,

Sadly, the dependency that you use to make requests to the api2pdf service, "request@2.88.0", is deprecated. We get warnings when installing your package, this will become a deal breaker sooner or later as it is no longer maintained.

You can see more details here:
https://github.com/request/request/issues/3142

Any plans to replace it (or rewrite the code really) soon?

Thank you.

**Comment by apexdodge** [comment]
Library completely rewritten for our v2 API with no dependencies. Available here: https://github.com/Api2Pdf/api2pdf.node/tree/2.0.0

Will merge into master after other libraries are completed for the other languages.

Thanks
